# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'assign5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for assign5

	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'MessageKit', '~> 3.0'

end
